import os
import yaml
import pandas as pd
import time
from dotenv import load_dotenv

try:
    from google import genai
    from google.genai import types
except ImportError:
    pass

try:
    import openai
except ImportError:
    pass

try:
    import anthropic
except ImportError:
    pass

load_dotenv()

with open("config.yml", "r") as file:
    config = yaml.safe_load(file)

provider = config["pipeline"]["provider"].lower()
model_to_use = config["pipeline"]["model_name"]
generation_temp = config["pipeline"]["temperature"]
input_filename = "data/processed/tcga_discordant_cases.csv"
output_dir = "data/generation_outputs"

os.makedirs(output_dir, exist_ok=True)

print(f"Loaded configuration: Using {provider.upper()} with model {model_to_use}")

system_instruction = """
You are an advanced Clinical Decision Support System (CDSS) specializing in genomic oncology.
Your task is to analyze transcriptomic data and resolve discordant prognostic risk classifications 
generated by multiple gene expression signatures for early-stage breast invasive carcinoma (BRCA).

You must provide a clinically actionable consensus summary that:
1. Synthesizes the biological pathways driving the discordant algorithmic outputs.
2. Explains the systematic root cause of the discordance based on the patient's transcriptomic footprint.
3. Provides a final clinical recommendation anchored in established oncological literature (e.g., NCCN guidelines).

Do not hallucinate data. Rely strictly on the provided transcriptomic markers.
"""

def generate_patient_summary(provider, model_name, temp, patient_id, clinical_data, signature_classifications, transcriptomic_data):
    """
    Routes the prompt to the correct LLM provider and standardises the output.
    """
    prompt = f"""
    Please analyze the following patient data to resolve the prognostic discordance:

    Patient ID: {patient_id}
    
    --- Clinical Metadata ---
    {clinical_data}

    --- Algorithmic Risk Classifications (1 = High Risk, 0 = Low Risk) ---
    {signature_classifications}

    --- Transcriptomic Profile (Select HGNC Gene Symbols & Expression Levels) ---
    {transcriptomic_data}
    
    Provide your resolution detailing the biological synthesis, systematic reasoning, and clinical actionability.
    """

    try:
        if provider == "gemini":
            api_key = os.getenv("GEMINI_API_KEY")
            client = genai.Client(api_key=api_key)
            generation_config = types.GenerateContentConfig(
                temperature=temp, 
                system_instruction=system_instruction
            )
            response = client.models.generate_content(
                model=model_name,
                contents=prompt,
                config=generation_config
            )
            return response.text
            
        elif provider == "openai":
            api_key = os.getenv("OPENAI_API_KEY")
            client = openai.OpenAI(api_key=api_key)
            response = client.chat.completions.create(
                model=model_name,
                temperature=temp,
                messages=[
                    {"role": "system", "content": system_instruction},
                    {"role": "user", "content": prompt}
                ]
            )
            return response.choices[0].message.content
            
        elif provider == "anthropic":
            api_key = os.getenv("ANTHROPIC_API_KEY")
            client = anthropic.Anthropic(api_key=api_key)
            response = client.messages.create(
                model=model_name,
                temperature=temp,
                system=system_instruction,
                max_tokens=1500, 
                messages=[
                    {"role": "user", "content": prompt}
                ]
            )
            return response.content[0].text
        
        elif provider == "deepseek":
            api_key = os.getenv("DEEPSEEK_API_KEY")
            client = openai.OpenAI(
                api_key=api_key, 
                base_url="https://api.deepseek.com" 
            )
            response = client.chat.completions.create(
                model=model_name,
                temperature=temp,
                messages=[
                    {"role": "system", "content": system_instruction},
                    {"role": "user", "content": prompt}
                ]
            )
            return response.choices[0].message.content
            
        else:
            raise ValueError(f"Provider '{provider}' is not supported. Check config.yml.")

    except Exception as e:
        print(f"Error generating summary for {patient_id}: {e}")
        return None

if not os.path.exists(input_filename):
    raise FileNotFoundError(
        f"Could not find {input_filename}. Run src/bioinformatics_pipeline.py first."
    )

df = pd.read_csv(input_filename)
if "Unnamed: 0" in df.columns:
    df = df.rename(columns={"Unnamed: 0": "patient_id"})
elif "patient_id" not in df.columns:
    raise ValueError("Could not find a patient identifier column in tcga_discordant_cases.csv")

sig_columns = [
    ("Oncotype DX", "OncotypeDX_Class"),
    ("PAM50", "Pam50_Class"),
    ("BCI", "BCI_Class"),
    ("Mammostrat", "Mammostrat_Class"),
    ("IHC4", "IHC4_Class"),
    ("Kim-10", "Kim10_Class"),
    ("IRRS-7", "IRRS7_Class"),
    ("Hu-11", "Hu11_Class"),
]

transcriptomic_columns = [
    "MKI67",
    "ESR1",
    "ERBB2",
    "PGR",
    "AURKA",
    "BCL2",
]

results = []

print(f"Initiating CDSS Pipeline using {provider.upper()}...\n")

for index, row in df.iterrows():
    print(f"Processing Patient: {row['patient_id']}...")
    
    clinical_fields = [
        ("years_to_birth", "Age at diagnosis"),
        ("pathologic_stage", "Pathologic stage"),
        ("histological_type", "Histological type"),
        ("ER.Status", "ER status"),
        ("PR.Status", "PR status"),
        ("HER2.Status", "HER2 status"),
        ("overall_survival", "Overall survival"),
        ("status", "Survival status"),
    ]
    clinical_meta = "\n".join(
        f"{label}: {row[column]}"
        for column, label in clinical_fields
        if column in row and pd.notna(row[column])
    )

    sig_classifications = "\n".join(
        f"{label}: {row[column]}"
        for label, column in sig_columns
        if column in row and pd.notna(row[column])
    )

    transcriptomics = "\n".join(
        f"{gene}: {row[gene]}"
        for gene in transcriptomic_columns
        if gene in row and pd.notna(row[gene])
    )
    
    summary = generate_patient_summary(
        provider=provider,
        model_name=model_to_use,
        temp=generation_temp,
        patient_id=row['patient_id'],
        clinical_data=clinical_meta,
        signature_classifications=sig_classifications,
        transcriptomic_data=transcriptomics
    )
    
    results.append({
        'patient_id': row['patient_id'],
        f'{provider}_summary': summary
    })
    
    print(f"--- SUCCESS: Generated summary for {row['patient_id']} ---")
    
    time.sleep(2)

results_df = pd.DataFrame(results)

output_filename = f"{output_dir}/{provider}_generation_results.csv"
results_df.to_csv(output_filename, index=False)

print(f"\nPipeline execution complete. Generation results saved to: {output_filename}")